// @ts-ignore
import type { Metadata } from "next";
// @ts-ignore
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import ToastProvider from "./components/ToastProvider";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import MobileFloatingButton from "./components/MobileFloatingButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex flex-col min-h-screen`}>
                <Navbar />
                <main>
                    <ToastProvider>{children}</ToastProvider>
                </main>
                <Footer />
                <MobileFloatingButton />
            </body>
        </html>
    );
}
